#!/bin/bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../ && pwd )"
BUILD_DIR=$ROOT_DIR/build

function echo_step {
  echo -e "\n\033[1m[$1]\033[0m"
}

function echo_cmd {
  echo -e ">> $1"
}

function transpile {
  node ./node_modules/.bin/babel $@ > /dev/null
}

echo_step 'Running Pre-Flight Operations'
cd $ROOT_DIR
echo_cmd 'Cleaning up traling install files'
rm -rf $BUILD_DIR
mkdir $BUILD_DIR

echo_step 'Installing SDK Module'
cd sdk
echo_cmd 'Downloading dependencies'
npm install > /dev/null
echo_cmd 'Transpiling source code'
mkdir -p $BUILD_DIR/sdk/src
transpile src/ -d $BUILD_DIR/sdk/src
echo_cmd 'Cloning dependencies + static resources'
cp -rp $ROOT_DIR/sdk/node_modules $BUILD_DIR/sdk/node_modules
cd $ROOT_DIR

echo_step 'Installing Server Module'
cd server
echo_cmd 'Downloading dependencies'
npm install > /dev/null
echo_cmd 'Cloning dependencies + static resources'
mkdir -p $BUILD_DIR/server
cp -rp $ROOT_DIR/server/node_modules $BUILD_DIR/server/node_modules
cp -rp $ROOT_DIR/server/config $BUILD_DIR/server/config
cp -rp $ROOT_DIR/server/*.grsb $BUILD_DIR/server/
echo_cmd 'Building static analysis specs'
node bin/fbTypesGenerator.js --inline-config="{\"graph\": {\"schema\": {\"bundle\": \"0cc346fffe9d8634ee241dc81286f8b1.grsb\"}}}" > /dev/null
echo_cmd 'Transpiling source code'
mkdir -p $BUILD_DIR/server/src
mkdir -p $BUILD_DIR/server/bin
transpile src/ -d $BUILD_DIR/server/src
transpile bin/ -d $BUILD_DIR/server/bin
transpile index.js -o $BUILD_DIR/server/index.js
cd $ROOT_DIR

echo_step 'Installing Client Module'
cd client
mkdir -p src/build
echo_cmd 'Downloading dependencies'
npm install > /dev/null
echo_cmd 'Building app bundle'
npm run build > /dev/null
echo_cmd 'Cloning dependencies + static resources'
mkdir -p $BUILD_DIR/client/src
cp -rp $ROOT_DIR/client/src/build $BUILD_DIR/client/src/build
cp -rpL $ROOT_DIR/client/src/css $BUILD_DIR/client/src/css
cp -rp $ROOT_DIR/client/src/index.html $BUILD_DIR/client/src/index.html
cd $ROOT_DIR

echo_step 'Cleaning source dirs'
rm -rf $ROOT_DIR/server $ROOT_DIR/sdk
echo_cmd 'Finished!'
